language: python
python:
    - "3.7"
install:
    - pip install tox
    - pip install pipenv
    - pipenv install
    - pipenv install --dev
script:
    - tox -e py27ci
    - tox -e py37ci
    - tox -e flake8
after_success:
    - coveralls